
class CARREGAR
{
public:
	void MainThread(void * lpParam);
	void Nomes();
	char * Nome_do_Main;
	char * Nome_do_Launcher;
	char * MainClassName;
	char * MainWindowName;
	char * Nome_da_Dll;
	char * IP_Server_and_Hard;
	char * FTP_User;
	char * FTP_Pass;
	char * Nome_da_DLL;
	char * Launcher_Window;
	char * Nome_das_Janelas;
	char * HackSplash_WebSite;
	char * Nome;
	char * Nome2;
	char * Serial;
	char * Versao;
	char * IP;
	char * Data;

	int BanSec_Update_time;
	int Carrega_serial_versao;
	int Virtual_Memory_Protect;
	int Verifica_Nome;
	int Splash_Screen;
	int Close_ClassName;
	int Close_Window;
	int LA_Detecta_ByFileSize;
	int Anti_Kill_Scans;
	int Detecta_Inject_API;
	int Delete_GetModuleHandle;
	int Ativa_CRC_Geral;
	int CRC_7_Terrains;
	int CRC_Player;
	int CRC_ProtectBMP;
	int CRC_WebZenLogoOZJ;
	int CRC_Launcher;
	int Detecta_Inject;
	int GlowDLL;
	int MinimizerDLL;
	int Detecta_Dump;
	int Token_Privileges;
	int Launcher_Ativo;
	int Detecta_Kill_by_Thread;
	int Log_Txt_Hack;
	int Message_Warning_En;
	int Detecta_Speed_Tickcount;
	int Detecta_PID;
	int LA_Detecta_byPipe;
	int Hack_Log_Upload;
	int Memory_Buffer_L;
	int Memory_Buffer_P;
	int Launcher_Mem_Protection;
	int Detecta_Window;
	int Detecta_Heuristica;
	int Detecta_Heuristica_Win;
	int Detecta_Heuristica_NC;
	int Detecta_Heuristica_Class;
	int Detecta_Speed_Performance;
	int Detecta_ClassName;
	int Server_Ban;
	int Detecta_Hide_Toolz;
	int Hardware_Ban;
	int Rebuild_Main_Data;
	int Log_File_Size_To_upload;
	int TESTE;

	//time detectors occours
	int DHide_occours;
	int DHard_occours;
	int DBan_occours;
	int DDump_occours;
	int DWindow_occours;
	int DClassName_occours;
	int DInject_occours;
	int DAPIInject_occours;
	int DAnti_Kill_occours;
	int DAnti_Kill_T_occours;
	int DAnti_Speed_P_occours;
	int DPID_occours;
	int DSpeed_occours;
	int DHeuristica_occours;
	int DHeuristica_Win_occours;
	int DHeuristica_NC_occours;
	int DHeuristica_Class_occours;
	int Virtual_Mem_occours;
	int DVerifica_occours;
	int DLauncher_Occours;

	long CRC_LauncherEXE;
	long CRC_PlayerBMD;
	long CRC_Protect;
	long CRC_WebLogo;
	long CRC_Terrain1;
	long CRC_Terrain2;
	long CRC_Terrain3;
	long CRC_Terrain4;
	long CRC_Terrain5;
	long CRC_Terrain6;
	long CRC_Terrain7;
};
extern CARREGAR carrega;